### ISSUE TITLE
Preserve date and time of the transferred files

### ISSUE THREAD

**Issue by tkzv** [whoozle/android-file-transfer-linux#149]
When files are transferred from/to mobile device, the new file is created with the current date/time rather than the date/time of the original file. Is it possible to create new files with the same modification time as the original?

Observed on Samsung SM-T525, using GUI, both for uploading and downloading, both from/to internal storage and SDXC card.

**Comment by pniederlag** [comment]
seems like a real requirement to me

**Comment by whoozle** [comment]
as far as I know, android is not allowing you to set this properties on objects, but I have to investigate current state of it.

**Comment by pniederlag** [comment]
If not possible to set the property on the android device, it would still be good to set the property on the file when downloading from android to PC. Right now all photos that I transfered from my mobile to my local PC have a recent timestamp. ;(

**Comment by whoozle** [comment]
Could you please run ./aft-mtp-cli and then type 'properties <any-path, e.g Music>' in the prompt, and then paste it here?

here's my output:
```
LGE Nexus 5> properties Music
properties supported: dc01 dc02 dc03 dc04 dc07 dc09 dc0b dc41 dc44 dce0 dc4e 
```

It looks like both of my nexuses (android versions 7 and 8) are supporting property codes dc08 and dc4e which are 'date modified' and 'date added'. Hopefully I can add support for that. 

But it could be somewhat tricky, since MTP is not telling all possible object properties, but returns them on per-object basis. 

I removed ctime/mtime support some time ago, because extra-request(s) (set/get ctime/mtime) per file was performance hit, but now my code utilizes more efficient batch properties request, and it should not affect performance at all. 

Anyway, ignore gory details and send me your properties :D I'll see what I can do for you
Thanks for your feedback!

**Comment by whoozle** [comment]
I remember now why I removed it. 

If you request mtime/ctime on per-object basis, android's MTP always returns 0, and then format it as 1970-1-1-…, it's useless. 

The only way I could request those properties is GetObjectPropertyList, which retrieves all properties for all children objects. :(

**Comment by whoozle** [comment]
added in ea9e6b669effb928c16619c982f64c91758237cd

**Comment by tkzv** [comment]
Sorry, my Samsung device got destroyed in an accident, can't test anything.
