### ISSUE TITLE
The instructions aren't clearn

### ISSUE THREAD

**Issue by icebunny08** [whoozle/android-file-transfer-linux#193]
I can't understand the instructions, I get errors like "...is a file, not a directory"

**Comment by whoozle** [comment]
could you please be more specific? what instructions? what did you do?

**Comment by jackieh** [comment]
Hi, I just wanted to comment on this issue in order to note that I found a lack of documentation for unmounting a device. I didn't find anything concerning unmounting when reviewing the [project page](https://whoozle.github.io/android-file-transfer-linux/), the [README.md documentation](https://github.com/whoozle/android-file-transfer-linux/blob/master/README.md), the [FAQ.md](https://github.com/whoozle/android-file-transfer-linux/blob/master/FAQ.md) documentation, a search in the [repository](https://github.com/whoozle/android-file-transfer-linux/search?q=unmount&unscoped_q=unmount) and [issues](https://github.com/whoozle/android-file-transfer-linux/issues?&q=unmount). I ran `aft-mtp-mount -h` and ` aft-mtp-cli -h` and didn't see anything concerning unmounting and I was unsuccessful finding any help option for the `android-file-transfer` command.

I ended up finding satisfactory info on the [Arch Linux wiki page](https://wiki.archlinux.org/index.php/Media_Transfer_Protocol) I originally found Android File Transfer in: "FUSE mounts can generally be unmounted using `fusermount -u mountpoint`." Running this command appears to have successfully unmounted my device after it was mounted.

I figure it might be obvious to use a `fusermount` command for anyone familiar with FUSE,  but it seems appropriate to not require a user less familiar with FUSE to look outside of the Android File Transfer documentation for this particular operation.

Let me know if you need any more specific details.

**Comment by whoozle** [comment]
Added as first entry of FAQ :D
https://github.com/whoozle/android-file-transfer-linux/blob/master/FAQ.md

**Comment by Maritsu** [comment]
> Hi, I just wanted to comment on this issue in order to note that I found a lack of documentation for unmounting a device. I didn't find anything concerning unmounting when reviewing the [project page](https://whoozle.github.io/android-file-transfer-linux/), the [README.md documentation](https://github.com/whoozle/android-file-transfer-linux/blob/master/README.md), the [FAQ.md](https://github.com/whoozle/android-file-transfer-linux/blob/master/FAQ.md) documentation, a search in the [repository](https://github.com/whoozle/android-file-transfer-linux/search?q=unmount&unscoped_q=unmount) and [issues](https://github.com/whoozle/android-file-transfer-linux/issues?&q=unmount). I ran `aft-mtp-mount -h` and ` aft-mtp-cli -h` and didn't see anything concerning unmounting and I was unsuccessful finding any help option for the `android-file-transfer` command.
> 
> I ended up finding satisfactory info on the [Arch Linux wiki page](https://wiki.archlinux.org/index.php/Media_Transfer_Protocol) I originally found Android File Transfer in: "FUSE mounts can generally be unmounted using `fusermount -u mountpoint`." Running this command appears to have successfully unmounted my device after it was mounted.
> 
> I figure it might be obvious to use a `fusermount` command for anyone familiar with FUSE, but it seems appropriate to not require a user less familiar with FUSE to look outside of the Android File Transfer documentation for this particular operation.
> 
> Let me know if you need any more specific details.

How is this not in the README along with the mount commands?! (also thanks @jackieh)
