### ISSUE TITLE
To hard to build for beginners 

### ISSUE THREAD

**Issue by Marcil01** [whoozle/android-file-transfer-linux#236]
I tried to to build the package using make, but no luck since i'm a newbie and instructions  in your readme File isn't really helpfully for new linux user, i found this PPA in lunchpad  https://launchpad.net/~samoilov-lex/+archive/ubuntu/aftl-stable.   but the version is old 

My request is 
1. Make the installation or building of the source file instructions very clear (don't cut corners please).
2. Why not just put your work in snap or Flathub  So we can easily install it and enjoy your amazing software instead of trying to figure this out for 3 hours.
Thank you very much your hard work.

**Comment by whoozle** [comment]
Hello, Marcil! 

I'm really sorry that it failed for you.
It looks like ubuntu instructions are a bit outdated, and require people to install qt4 which is unsupported and old. Instructions themselves don't have any corners cut, it should just work as they are. 
I addressed instruction update in 1cb25d4bd696e39740d858cafe453331e0d040c2

It turned out that Q4 support was broken as well, addressed in ee204473145f36e030ba573ba5f0233fcab6ffa0

So if you still want to try compiling it, before going through instructions again

1. `apt-get install qt5-default`
2. `rm -rf build` in android-file-transfer-linux directory
3. go through building instruction again. 

Should be fine this time.

It's also a good idea to include build failures on the ticket. 
Thanks

**Comment by xaverdh** [comment]
Not sure if this helps, but if you have access to the [nix](https://nixos.org/nix/) package manager (which can be installed on top of most linux distributions, side by side with any native package manager), I packaged it for nix.

**Comment by whoozle** [comment]
@xaverdh thanks!

**Comment by whoozle** [comment]
Also if you go releases -> pick release, there's AppImage available

**Comment by whoozle** [comment]
added snap package, test it if you can :)

https://snapcraft.io/android-file-transfer-linux
