### ISSUE TITLE
Issues with Nintendo Switch

### ISSUE THREAD

**Issue by mid-kid** [whoozle/android-file-transfer-linux#261]
The Switch recently(ish?) added support for transferring screenshots and clips over MTP. This can be accessed through "System Settings → Data Management → Manage Screenshots and Videos → Copy to PC via USB Connection".
There's two problems with this:
* If the program isn't on or doesn't respond, the console will automatically stop the MTP connection.
* After downloading a file, or when opening the right click menu, or during some other actions, the program just hangs.

The first issue is a bit of a catch-22, since the console will disconnect when the program isn't running, and the program will refuse to run if it can't connect to the console.

Right now, the only way to use this program with the console, is by pressing the "connect" option on the console, and opening the program within the timeout before the console disconnects, then quickly navigate to the file you want, select it, don't(!) right click, but press CTRL+D instead, select save destination, and when the file is done downloading (at 100%, it will hang), unplug the cable, and repeat for every file. Needless to say, this is a terrible workflow.

I believe the first issue would be possible to solve by having the program wait for a device to connect, and try to reconnect as soon as it unplugs. I'm not sure about the cause behind the second issue, however.

EDIT: These issues are present on 4.0, I haven't tested 4.1 yet.

**Comment by whoozle** [comment]
Nice, I didn't know that, I'll test it (hopefully right away)

Please update to 4.1 and test it, because 4.0 has a regression which broke many android devices.
I found that standard requires to pass container header/data (e.g. type of the transfer and let's say object property value) in separate USB bulk packets. This makes Zune and some other devices work just fine. Weird, but my google devices are fine with it too.
In 4.1 there's Zune check and old behaviour (single USB bulk packet) restored.

**Comment by whoozle** [comment]
Ignore this, updating won't help. They use really tiny and incomplete MTP implementation. No error reporting, whatsoever. Fix is on its way

**Comment by whoozle** [comment]
Should be fixed in 546665c61f9bd00cb721bf5da0d78d5db5f05115

I briefly tested most of the things (excluding fuse mount). Thumbnails, navigation and download works fine. Uploading is not supported by device itself.

![image](https://user-images.githubusercontent.com/480115/103176794-c3963100-486c-11eb-82a0-255825c9da52.png)

**Comment by whoozle** [comment]
You can either build it from source or wait Travis finishes its jobs and download build for macosx/appimage from 
https://github.com/whoozle/android-file-transfer-linux/releases/tag/continuous

**Comment by mid-kid** [comment]
Thanks a ton for fixing it. I've tested the new commit, and it works perfectly!

**Comment by whoozle** [comment]
Np, have fun :+1:  I'm adding multiple devices support and hopefully the new release will be out soon.
