### ISSUE TITLE
Device::Find failed:Device is already used by another process

### ISSUE THREAD

**Issue by stskyblade** [whoozle/android-file-transfer-linux#275]
I failed to mount my mtp device to a directory. Error: `Device::Find failed:Device is already used by another process`

I use:
Arch linux
KDE, Dolphin

I can view file in mtp device using Dolphine, but can't mount it by executing `aft-mtp-mount ~/mnt`.

**Comment by whoozle** [comment]
MTP is exclusive, meaning that you can't access to the same device using different apps. You have to close/kill any apps accessing your device first. Try running UI app, it will offer you to kill the other processes.

**Comment by stskyblade** [comment]
I found my mtp device is used by `kiod5`. I can mount it if I killed `kiod5`.

**Comment by jehoshua7** [comment]
With a fresh install of Kubuntu 21.10, I found that I could no longer use `go-mtpfs`

> 2022/04/17 12:10:11 OpenSession failed: LIBUSB_ERROR_IO; attempting reset
2022/04/17 12:10:12 selectStorages failed: EOF

I had never heard of **'aft'** , literally stumbled upon it searching for an answer to mount this Galaxy S5. Also the problem was compounded by Dolphin connecting automatically to the phone.

Initially I got 

`aft-mtp-mount ~/myphone`

> Device::Find failed:Device is already used by another process
connect failed: no MTP device found

then found this issue, went into the GUI and killed the process that was using the phone. It was `kiod5`. Exited the GUI and ..

`aft-mtp-mount ~/myphone`

> your device does not have android EditObject extension, mounting read-only

I only need read-only mode. It mounted just fine, exactly as required.

So, a **HUGE** thanks to the developers of "android-file-transfer-linux"
